### PR TITLE
Ported to Python 3

### PR DESCRIPTION
**Pull request by kingroryg**
Ported basic syntactical irregularities to py3 . Tests passing under py3 .

### CODE REVIEW

**Comment by rhsimplex** [comment]
Thanks @saru95, I will review this monday

**Comment by rhsimplex** [comment]
Can you do me a favor and add a file `.travis.yml` to the root of the project?

Just paste this in there, so we can trigger automated testing:

``` yml
language: python
python:
  - 3.4

services:
  - elasticsearch

# From http://conda.pydata.org/docs/travis.html
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy scikit-image pytest
  - source activate test-environment
  - python setup.py install

script: py.test -s -v
```

**Comment by kingroryg** [comment]
Sure , can you give me time till tomorrow ?

EDIT : Just noticed, its already been done .

**Comment by rhsimplex** [comment]
Yeah, just add that to the root of your fork, commit and push.  That _should_ trigger CI, hopefully =)

**Comment by kingroryg** [comment]
Tests are running under Python 2.7 . Shouldn't they be running in Python 3 ?
On my remote machine I am running ,

```
$  python3 -m pytest
```

@rhsimplex Could you change Travis CI to run tests under Python 3 ?

**Comment by rhsimplex** [comment]
Merged.  Turns out you can't have different testing environments per branch.  Anyway, thanks for your help! Now we're python3!

**Pull request merged**
